
const FETCH_MOVIES: string = 'FETCH_MOVIES';
const FETCH_TOP_MOVIES: string = 'FETCH_TOP_MOVIES';
const SELECT_MOVIE: string = 'SELECT_MOVIE';
const FETCH_MOVIE: string = 'FETCH_MOVIE';
const FETCH_REQUEST: string = 'FETCH_REQUEST';
const FETCH_ERROR: string = 'FETCH_ERROR';

export default {
    FETCH_MOVIES,
    FETCH_TOP_MOVIES,
    SELECT_MOVIE,
    FETCH_MOVIE,
    FETCH_REQUEST,
    FETCH_ERROR
}